language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - hyyyyjin@naver.com

before_delpoy:
  - zip -r springboot_webservice *
  - mkdir -p deploy
  - mv  springboot_webservice.zip deploy/springboot_webservice.zip

deploy:
  - provider: storage
    access_key_id: $GCP_ACCESS_KEY
    secret_access_key: : $GCP_SECRET_KEY
    bucket : springboot-build #생성한 storage 이름
    region : asia-northeast1
    skip_cleanup: true
    acl : private
    local_dir : deploy
    wait-until-deployed: true


